/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ReagentRow = IDL.Record({
  'cpt' : IDL.Float64,
  'name' : IDL.Text,
  'volume' : IDL.Float64,
  'price' : IDL.Float64,
  'mlCost' : IDL.Float64,
});
export const Session = IDL.Record({
  'reagents' : IDL.Vec(ReagentRow),
  'name' : IDL.Text,
  'divisor' : IDL.Float64,
});

export const idlService = IDL.Service({
  'deleteSession' : IDL.Func([IDL.Text], [], []),
  'getSession' : IDL.Func([IDL.Text], [Session], ['query']),
  'listSessions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Session))],
      ['query'],
    ),
  'saveSession' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64, IDL.Float64)),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ReagentRow = IDL.Record({
    'cpt' : IDL.Float64,
    'name' : IDL.Text,
    'volume' : IDL.Float64,
    'price' : IDL.Float64,
    'mlCost' : IDL.Float64,
  });
  const Session = IDL.Record({
    'reagents' : IDL.Vec(ReagentRow),
    'name' : IDL.Text,
    'divisor' : IDL.Float64,
  });
  
  return IDL.Service({
    'deleteSession' : IDL.Func([IDL.Text], [], []),
    'getSession' : IDL.Func([IDL.Text], [Session], ['query']),
    'listSessions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Session))],
        ['query'],
      ),
    'saveSession' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64, IDL.Float64)),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };